modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="streamdecked"

version="${mod_version}"

displayName="${mod_name}"

authors="Wolfieboy09"

description='''
A library for mods to have functionality with Elgato's Stream Decks
'''

[[mixins]]
config="streamdecked.mixins.json"

[[dependencies.streamdecked]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.streamdecked]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
